#!/bin/sh

RED="\\033[1;31m"
YELLOW="\\033[1;33m"
NOCOLOR="\\033[0m"

if [ "$#" -eq 0 ]
then
    echo "One argument needs to be given. Both relative, and absolute file paths are supported. Exiting (1)."
    exit 1
fi

if [ "$#" -gt 1 ]
then
    echo "Multiple arguments are not supported. Exiting (2)."
    exit 2
fi

if [ ! -f "$1" ]
then
    echo "The given argument is not an existing file. Exiting (3)."
    exit 3
fi

input_filename="$1"

if [ ! -r "$input_filename" ]
then
    echo "Input file is not readable by you. Exiting (4)."
    exit 4
fi

input_filepath=$(dirname "$input_filename")

if [ ! -w "$input_filepath" ]
then
    echo "Destination directory is not writable by you. Exiting (5)."
    exit 5
fi

filename_extracted_from_path=$(basename "$input_filename")
filename_without_enc_extension="${filename_extracted_from_path%.enc}"

if [ "$filename_extracted_from_path" = "$filename_without_enc_extension" ]
then
    # the file has a different than .enc extension or no extension at all
    # what we do now, is that we append .dec extention to the file name
    output_filename="$input_filepath/$filename_extracted_from_path".dec
else
    # the file has the .enc extension
    # what we do now, is that we use the file name without .enc extension
    output_filename="$input_filepath/$filename_without_enc_extension"
fi

if [ -f "$output_filename" ]
then
    echo "Destination file exists. Exiting (6)."
    exit 6
fi

if ! pv --wait "$input_filename" | openssl enc -aes-256-cbc -md sha256 -salt -out "$output_filename" -d 2> /dev/null
then
    echo "${RED}Decryption failed. Exiting (7).${NOCOLOR}"

    if [ -f "$output_filename" ]
    then
        rm "$output_filename"
    fi

    exit 7
else
    echo "${YELLOW}Decryption successful.${NOCOLOR}"

    exit 0
fi
